# render.yaml

services:
  - type: static_site
    name: Team-13-All-You-Can-Gym-Frontend # Set your service name
    pullRequestOnly: false
    static:
      rewrites:
        # This rule serves index.html for any path that doesn't match a static file.
        # This is necessary for single-page applications like React.
        - source: '/*'
          destination: /index.html